# General settings
run_fastp: true  # Whether to run fastp for read trimming
read_type: "paired"  # Options: "paired" or "single"

executables:
  fastp: "/path/to/fastp"
  fastqc: "/path/to/fastqc"
  star: "/path/to/STAR"
  featurecounts: "/path/to/featureCounts"
  python: "/usr/bin/python3"  # Path to Python interpreter

# Directories
input_dir: "data"
output_dir: "output"
temp_dir: "tmp"

# Samples. Either list of sample names or a file containing sample names.
# If both are provided, the file will take precedence.
samples_file: "samples.txt"  # Path to a file containing sample names (one per line). 
samples:
  - sample1
  - sample2

# fastqc settings
fastqc_before_trimming: true  # Run FastQC before trimming
fastqc_after_trimming: true  # Run FastQC after trimming
fastqc_mem_mb: 1000  # Memory limit for FastQC in MB

# fastp settings
fastp_threads: 4  # Number of threads for fastp
fastp_params: ""  # Additional custom parameters for fastp (leave empty by default)

# STAR settings
star_threads: 10  # Number of threads for STAR
star_genome_index: "/path/to/genomeDir"  # Path to STAR genome index
annotation_gtf: "/path/to/annotation.gtf"  # Path to GTF file
sjdb_overhang: 99  # Default value for sjdbOverhang
outFilterMultimapNmax: 50  # Default value for outFilterMultimapNmax
outBAMsortingThreadN: 10  # Default value for BAM sorting threads
clip3AdapterSeq: "CTGTCTCTTATACACATCT"  # Default adapter sequence
quant_mode: "GeneCounts"  # Default quantification mode (Check if this is correct!)
star_params: ""  # Additional custom parameters for STAR (leave empty by default)
star_mem_mb: 35000 # Memory limit for STAR in MB

# featureCounts settings
featurecounts_threads: 5  # Number of threads for featureCounts
generate_saf: true
exon_saf: "/path/to/exon_SAF"  # Path to SAF file for exon mode
intron_saf: "/path/to/intron_SAF"  # Path to SAF file for intron mode
featurecounts_params: "-p --largestOverlap --primary"  # Additional custom parameters for featureCounts

# Merge BAM settings
merge_priority: "exon"  # Default priority for merging (exon or intron)
merge_threads: 10  # Number of threads for sorting
merge_index: true  # Whether to index the output BAM file

# Quantification and stats settings
quant_threads: 10  # Number of threads for quantification and stats

# Cleanup settings
cleanup_intermediates: false  # Whether to clean up intermediate files
